### PR TITLE
first run-through - introduction chapter

### PR DESCRIPTION
**Pull request by xlfe**
@prasimix do you want me to generate a diff so you can see changes too?

### CODE REVIEW

**Comment by xlfe** [comment]
I've also noticed some of the numerals in the tables don't seem to display correctly on my system.

**Comment by prasimix** [comment]
I just added combinumerals font that you need for displaying numerals in tables correctly

**Comment by prasimix** [comment]
> @prasimix do you want me to generate a diff so you can see changes too?

No it is not necessary, just keep "track changes ... Record" active.

**Comment by xlfe** [comment]
okay I turned off track changes though because (before I made any changes) I thought git would show what changed.

**Comment by prasimix** [comment]
Nothing is lost, you just turned off "Show" but importantly the "Record" is still active, therefore I can see all changes:
Screenshot from 2019-11-23 09-51-28

**Comment by prasimix** [comment]
I forgot to say: feel free to add your comments, questions, suggestions using Writer Comment (Ctrl+Alt+C) option if necessary.

**Comment by xlfe** [comment]
Ah great. Is this the sort of proofreading / changes you're looking for?

Cheers

**Comment by prasimix** [comment]
Absolutely!

**Pull request merged**
